### ISSUE TITLE
Pre-trained Weights

### ISSUE THREAD

**Issue by EscVM** [hamidriasat/DDRNets#1]
Hi @hamidriasat!

Do you have any pre-trained weights to share?

Thanks

**Comment by hamidriasat** [comment]
Sorry, I trained it on my own custom dataset.

**Comment by EscVM** [comment]
No problem! I'm gonna train on Cityscapes and share with you the weights.

**Comment by hamidriasat** [comment]
@EscVM have you trained it on Cityscapes?

**Comment by EscVM** [comment]
Hi @hamidriasat! Yes, I trained it, but I obtained very awful results :) I didn't have enough time to catch the problem, and so I left it. If you want, I can share my notebook with you!

**Comment by hamidriasat** [comment]
Yes kindly share the notebook.
